name: SurvivalFreecam
description: Survival Freecam Bukkit Plugin, By Excel#8392
version: 1.0
main: com.gmail.excel8392.survivalfreecam.SurvivalFreecam
api-version: 1.13
depend: [NPCLib]
commands:
  freecam:
    description: Freecam mode
permissions:
  survivalfreecam.toggle:
    description: Allows a player to enter freecam mode
